src/Entity/Destination.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DestinationRepository")
 */
class Destination
{
    use BaseEntityTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_de_la_ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $longitude;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Voyage", mappedBy="id_destination", orphanRemoval=true)
     */
    private $voyages;

    public function __construct()
    {
        $this->voyages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDeLaVille(): ?string
    {
        return $this->nom_de_la_ville;
    }

    public function setNomDeLaVille(string $nom_de_la_ville): self
    {
        $this->nom_de_la_ville = $nom_de_la_ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return Collection|Voyage[]
     */
    public function getVoyages(): Collection
    {
        return $this->voyages;
    }

    public function addVoyage(Voyage $voyage): self
    {
        if (!$this->voyages->contains($voyage)) {
            $this->voyages[] = $voyage;
            $voyage->setIdDestination($this);
        }

        return $this;
    }

    public function removeVoyage(Voyage $voyage): self
    {
        if ($this->voyages->contains($voyage)) {
            $this->voyages->removeElement($voyage);
            // set the owning side to null (unless already changed)
            if ($voyage->getIdDestination() === $this) {
                $voyage->setIdDestination(null);
            }
        }

        return $this;
    }
}

src/Form/DestinationType.php
<?php

namespace App\Form;

use App\Entity\Destination;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DestinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_de_la_ville')
            ->add('pays')
            ->add('latitude')
            ->add('longitude')
            ->add('created')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Destination::class,
        ]);
    }
}

src/Controller/DestinationController.php
<?php

namespace App\Controller;

use App\Entity\Destination;
use App\Form\DestinationType;
use App\Repository\DestinationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/destination")
 */
class DestinationController extends AbstractController
{
    /**
     * @Route("/", name="destination_index", methods={"GET"})
     */
    public function index(DestinationRepository $destinationRepository): Response
    {
        return $this->render('destination/index.html.twig', [
            'destinations' => $destinationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="destination_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $destination = new Destination();
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($destination);
            $entityManager->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('destination/new.html.twig', [
            'destination' => $destination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="destination_show", methods={"GET"})
     */
    public function show(Destination $destination): Response
    {
        return $this->render('destination/show.html.twig', [
            'destination' => $destination,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="destination_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Destination $destination): Response
    {
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('destination_index');
        }

        return $this->render('destination/edit.html.twig', [
            'destination' => $destination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="destination_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Destination $destination): Response
    {
        if ($this->isCsrfTokenValid('delete'.$destination->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($destination);
            $entityManager->flush();
        }

        return $this->redirectToRoute('destination_index');
    }
}

templates/destination/_delete_form.html.twig
<form method="post" action="{{ path('destination_delete', {'id': destination.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ destination.id) }}">
    <button class="btn">Delete</button>
</form>

templates/destination/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/destination/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Destination{% endblock %}

{% block body %}
    <h1>Edit Destination</h1>

    {{ include('destination/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('destination_index') }}">back to list</a>

    {{ include('destination/_delete_form.html.twig') }}
{% endblock %}

templates/destination/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination index{% endblock %}

{% block body %}
    <h1>Destination index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom_de_la_ville</th>
                <th>Pays</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Id</th>
                <th>Created</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for destination in destinations %}
            <tr>
                <td>{{ destination.nomDeLaVille }}</td>
                <td>{{ destination.pays }}</td>
                <td>{{ destination.latitude }}</td>
                <td>{{ destination.longitude }}</td>
                <td>{{ destination.id }}</td>
                <td>{{ destination.created ? destination.created|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('destination_show', {'id': destination.id}) }}">show</a>
                    <a href="{{ path('destination_edit', {'id': destination.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('destination_new') }}">Create new</a>
{% endblock %}

templates/destination/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Destination{% endblock %}

{% block body %}
    <h1>Create new Destination</h1>

    {{ include('destination/_form.html.twig') }}

    <a href="{{ path('destination_index') }}">back to list</a>
{% endblock %}

templates/destination/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination{% endblock %}

{% block body %}
    <h1>Destination</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom_de_la_ville</th>
                <td>{{ destination.nomDeLaVille }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ destination.pays }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ destination.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ destination.longitude }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ destination.id }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ destination.created ? destination.created|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('destination_index') }}">back to list</a>

    <a href="{{ path('destination_edit', {'id': destination.id}) }}">edit</a>

    {{ include('destination/_delete_form.html.twig') }}
{% endblock %}