src/Entity/Voyage.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VoyageRepository")
 */
class Voyage
{
   use BaseEntityTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_de_voyage;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_de_km_parcourues;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destination", inversedBy="voyages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_destination;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Portfolio", mappedBy="id_voyage", orphanRemoval=true)
     */
    private $portfolios;

    public function __construct()
    {
        $this->portfolios = new ArrayCollection();
    }


    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDeVoyage(): ?\DateTimeInterface
    {
        return $this->date_de_voyage;
    }

    public function setDateDeVoyage(\DateTimeInterface $date_de_voyage): self
    {
        $this->date_de_voyage = $date_de_voyage;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getNbDeKmParcourues(): ?int
    {
        return $this->nb_de_km_parcourues;
    }

    public function setNbDeKmParcourues(?int $nb_de_km_parcourues): self
    {
        $this->nb_de_km_parcourues = $nb_de_km_parcourues;

        return $this;
    }

    public function getIdDestination(): ?Destination
    {
        return $this->id_destination;
    }

    public function setIdDestination(?Destination $id_destination): self
    {
        $this->id_destination = $id_destination;

        return $this;
    }

    /**
     * @return Collection|Portfolio[]
     */
    public function getPortfolios(): Collection
    {
        return $this->portfolios;
    }

    public function addPortfolio(Portfolio $portfolio): self
    {
        if (!$this->portfolios->contains($portfolio)) {
            $this->portfolios[] = $portfolio;
            $portfolio->setIdVoyage($this);
        }

        return $this;
    }

    public function removePortfolio(Portfolio $portfolio): self
    {
        if ($this->portfolios->contains($portfolio)) {
            $this->portfolios->removeElement($portfolio);
            // set the owning side to null (unless already changed)
            if ($portfolio->getIdVoyage() === $this) {
                $portfolio->setIdVoyage(null);
            }
        }

        return $this;
    }
}

src/Form/VoyageType.php
<?php

namespace App\Form;

use App\Entity\Voyage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_de_voyage')
            ->add('note')
            ->add('nb_de_km_parcourues')
            ->add('created')
            ->add('id_destination')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Voyage::class,
        ]);
    }
}

src/Controller/VoyageController.php
<?php

namespace App\Controller;

use App\Entity\Voyage;
use App\Form\VoyageType;
use App\Repository\VoyageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/voyage")
 */
class VoyageController extends AbstractController
{
    /**
     * @Route("/", name="voyage_index", methods={"GET"})
     */
    public function index(VoyageRepository $voyageRepository): Response
    {
        return $this->render('voyage/index.html.twig', [
            'voyages' => $voyageRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="voyage_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $voyage = new Voyage();
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($voyage);
            $entityManager->flush();

            return $this->redirectToRoute('voyage_index');
        }

        return $this->render('voyage/new.html.twig', [
            'voyage' => $voyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voyage_show", methods={"GET"})
     */
    public function show(Voyage $voyage): Response
    {
        return $this->render('voyage/show.html.twig', [
            'voyage' => $voyage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="voyage_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Voyage $voyage): Response
    {
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('voyage_index');
        }

        return $this->render('voyage/edit.html.twig', [
            'voyage' => $voyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voyage_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Voyage $voyage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voyage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($voyage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('voyage_index');
    }
}

templates/voyage/_delete_form.html.twig
<form method="post" action="{{ path('voyage_delete', {'id': voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voyage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/voyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/voyage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voyage{% endblock %}

{% block body %}
    <h1>Edit Voyage</h1>

    {{ include('voyage/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('voyage_index') }}">back to list</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}

templates/voyage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage index{% endblock %}

{% block body %}
    <h1>Voyage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Date_de_voyage</th>
                <th>Note</th>
                <th>Nb_de_km_parcourues</th>
                <th>Id</th>
                <th>Created</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for voyage in voyages %}
            <tr>
                <td>{{ voyage.titre }}</td>
                <td>{{ voyage.description }}</td>
                <td>{{ voyage.dateDeVoyage ? voyage.dateDeVoyage|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ voyage.note }}</td>
                <td>{{ voyage.nbDeKmParcourues }}</td>
                <td>{{ voyage.id }}</td>
                <td>{{ voyage.created ? voyage.created|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('voyage_show', {'id': voyage.id}) }}">show</a>
                    <a href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('voyage_new') }}">Create new</a>
{% endblock %}

templates/voyage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voyage{% endblock %}

{% block body %}
    <h1>Create new Voyage</h1>

    {{ include('voyage/_form.html.twig') }}

    <a href="{{ path('voyage_index') }}">back to list</a>
{% endblock %}

templates/voyage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage{% endblock %}

{% block body %}
    <h1>Voyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ voyage.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ voyage.description }}</td>
            </tr>
            <tr>
                <th>Date_de_voyage</th>
                <td>{{ voyage.dateDeVoyage ? voyage.dateDeVoyage|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ voyage.note }}</td>
            </tr>
            <tr>
                <th>Nb_de_km_parcourues</th>
                <td>{{ voyage.nbDeKmParcourues }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ voyage.id }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ voyage.created ? voyage.created|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('voyage_index') }}">back to list</a>

    <a href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}